### ISSUE TITLE
paper is very short

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-518#2]

**Comment by mrobinson0026** [comment]
Very short? May I have more in-depth feedback? The word count is over 1,200 with no quotes. The ask was for 2-3 pages in Piazza.

**Comment by laszewsk** [comment]
maybe i looked at wrong paper.

**Comment by laszewsk** [comment]
I saw 1.5 pages. Feedback will be given when we look at it on Monday
